Spring:
  application:
       name: Config-Default
       
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: sa123     
      
# eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
